sonar.projectKey=pgko-dev_pgko
sonar.projectName=pgko
sonar.host.url=https://sonarcloud.io
sonar.organization=pgko-dev
sonar.sourceEncoding=UTF-8
sonar.sources=.
sonar.tests=.
sonar.test.inclusions=**/*.test.*,**/*.spec.*,**/__test__/**,**/__tests__/**,**/test/**,**/tests/**
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/out/**,**/coverage/**,**/.scannerwork/**,**/.cache/**,**/.tanstack/**,**/vendor/**,**/*.d.ts,**/*.gen.ts,**/*.min.js,**/*.min.css
sonar.coverage.exclusions=**/*

sonar.cpd.exclusions=packages/i18n/src/**
