/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CollaborationsRouteImport } from './routes/collaborations'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TosRouteImport } from './routes/tos'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth/forgot-password'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as BundlesIndexRouteImport } from './routes/bundles/index'
import { Route as BundlesBundleIdRouteImport } from './routes/bundles/$bundleId'
import { Route as BundlesUploadRouteImport } from './routes/bundles/upload'
import { Route as UsersIndexRouteImport } from './routes/users.index'
import { Route as UsersJointIdRouteImport } from './routes/users.$jointId'
import { Route as BundlesBundleIdIndexRouteImport } from './routes/bundles/$bundleId.index'
import { Route as BundlesBundleIdDraftRouteImport } from './routes/bundles/$bundleId.draft'
import { Route as BundlesBundleIdManageRouteImport } from './routes/bundles/$bundleId.manage'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CollaborationsRoute = CollaborationsRouteImport.update({
  id: '/collaborations',
  path: '/collaborations',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TosRoute = TosRouteImport.update({
  id: '/tos',
  path: '/tos',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const BundlesIndexRoute = BundlesIndexRouteImport.update({
  id: '/bundles/',
  path: '/bundles/',
  getParentRoute: () => rootRouteImport,
} as any)
const BundlesBundleIdRoute = BundlesBundleIdRouteImport.update({
  id: '/bundles/$bundleId',
  path: '/bundles/$bundleId',
  getParentRoute: () => rootRouteImport,
} as any)
const BundlesUploadRoute = BundlesUploadRouteImport.update({
  id: '/bundles/upload',
  path: '/bundles/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersIndexRoute = UsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersJointIdRoute = UsersJointIdRouteImport.update({
  id: '/users/$jointId',
  path: '/users/$jointId',
  getParentRoute: () => rootRouteImport,
} as any)
const BundlesBundleIdIndexRoute = BundlesBundleIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BundlesBundleIdRoute,
} as any)
const BundlesBundleIdDraftRoute = BundlesBundleIdDraftRouteImport.update({
  id: '/draft',
  path: '/draft',
  getParentRoute: () => BundlesBundleIdRoute,
} as any)
const BundlesBundleIdManageRoute = BundlesBundleIdManageRouteImport.update({
  id: '/manage',
  path: '/manage',
  getParentRoute: () => BundlesBundleIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/collaborations': typeof CollaborationsRoute
  '/settings': typeof SettingsRoute
  '/tos': typeof TosRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/bundles/$bundleId': typeof BundlesBundleIdRouteWithChildren
  '/bundles/upload': typeof BundlesUploadRoute
  '/users/$jointId': typeof UsersJointIdRoute
  '/bundles/': typeof BundlesIndexRoute
  '/users/': typeof UsersIndexRoute
  '/bundles/$bundleId/draft': typeof BundlesBundleIdDraftRoute
  '/bundles/$bundleId/manage': typeof BundlesBundleIdManageRoute
  '/bundles/$bundleId/': typeof BundlesBundleIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/collaborations': typeof CollaborationsRoute
  '/settings': typeof SettingsRoute
  '/tos': typeof TosRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/bundles/upload': typeof BundlesUploadRoute
  '/users/$jointId': typeof UsersJointIdRoute
  '/bundles': typeof BundlesIndexRoute
  '/users': typeof UsersIndexRoute
  '/bundles/$bundleId/draft': typeof BundlesBundleIdDraftRoute
  '/bundles/$bundleId/manage': typeof BundlesBundleIdManageRoute
  '/bundles/$bundleId': typeof BundlesBundleIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/about': typeof AboutRoute
  '/collaborations': typeof CollaborationsRoute
  '/settings': typeof SettingsRoute
  '/tos': typeof TosRoute
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/bundles/$bundleId': typeof BundlesBundleIdRouteWithChildren
  '/bundles/upload': typeof BundlesUploadRoute
  '/users/$jointId': typeof UsersJointIdRoute
  '/bundles/': typeof BundlesIndexRoute
  '/users/': typeof UsersIndexRoute
  '/bundles/$bundleId/draft': typeof BundlesBundleIdDraftRoute
  '/bundles/$bundleId/manage': typeof BundlesBundleIdManageRoute
  '/bundles/$bundleId/': typeof BundlesBundleIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/collaborations'
    | '/settings'
    | '/tos'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/bundles/$bundleId'
    | '/bundles/upload'
    | '/users/$jointId'
    | '/bundles/'
    | '/users/'
    | '/bundles/$bundleId/draft'
    | '/bundles/$bundleId/manage'
    | '/bundles/$bundleId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/collaborations'
    | '/settings'
    | '/tos'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/bundles/upload'
    | '/users/$jointId'
    | '/bundles'
    | '/users'
    | '/bundles/$bundleId/draft'
    | '/bundles/$bundleId/manage'
    | '/bundles/$bundleId'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/about'
    | '/collaborations'
    | '/settings'
    | '/tos'
    | '/_auth/forgot-password'
    | '/_auth/login'
    | '/_auth/register'
    | '/bundles/$bundleId'
    | '/bundles/upload'
    | '/users/$jointId'
    | '/bundles/'
    | '/users/'
    | '/bundles/$bundleId/draft'
    | '/bundles/$bundleId/manage'
    | '/bundles/$bundleId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  AboutRoute: typeof AboutRoute
  CollaborationsRoute: typeof CollaborationsRoute
  SettingsRoute: typeof SettingsRoute
  TosRoute: typeof TosRoute
  BundlesBundleIdRoute: typeof BundlesBundleIdRouteWithChildren
  BundlesUploadRoute: typeof BundlesUploadRoute
  UsersJointIdRoute: typeof UsersJointIdRoute
  BundlesIndexRoute: typeof BundlesIndexRoute
  UsersIndexRoute: typeof UsersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collaborations': {
      id: '/collaborations'
      path: '/collaborations'
      fullPath: '/collaborations'
      preLoaderRoute: typeof CollaborationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tos': {
      id: '/tos'
      path: '/tos'
      fullPath: '/tos'
      preLoaderRoute: typeof TosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/bundles/': {
      id: '/bundles/'
      path: '/bundles'
      fullPath: '/bundles/'
      preLoaderRoute: typeof BundlesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bundles/$bundleId': {
      id: '/bundles/$bundleId'
      path: '/bundles/$bundleId'
      fullPath: '/bundles/$bundleId'
      preLoaderRoute: typeof BundlesBundleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bundles/upload': {
      id: '/bundles/upload'
      path: '/bundles/upload'
      fullPath: '/bundles/upload'
      preLoaderRoute: typeof BundlesUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/': {
      id: '/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof UsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/$jointId': {
      id: '/users/$jointId'
      path: '/users/$jointId'
      fullPath: '/users/$jointId'
      preLoaderRoute: typeof UsersJointIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bundles/$bundleId/': {
      id: '/bundles/$bundleId/'
      path: '/'
      fullPath: '/bundles/$bundleId/'
      preLoaderRoute: typeof BundlesBundleIdIndexRouteImport
      parentRoute: typeof BundlesBundleIdRoute
    }
    '/bundles/$bundleId/draft': {
      id: '/bundles/$bundleId/draft'
      path: '/draft'
      fullPath: '/bundles/$bundleId/draft'
      preLoaderRoute: typeof BundlesBundleIdDraftRouteImport
      parentRoute: typeof BundlesBundleIdRoute
    }
    '/bundles/$bundleId/manage': {
      id: '/bundles/$bundleId/manage'
      path: '/manage'
      fullPath: '/bundles/$bundleId/manage'
      preLoaderRoute: typeof BundlesBundleIdManageRouteImport
      parentRoute: typeof BundlesBundleIdRoute
    }
  }
}

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface BundlesBundleIdRouteChildren {
  BundlesBundleIdDraftRoute: typeof BundlesBundleIdDraftRoute
  BundlesBundleIdManageRoute: typeof BundlesBundleIdManageRoute
  BundlesBundleIdIndexRoute: typeof BundlesBundleIdIndexRoute
}

const BundlesBundleIdRouteChildren: BundlesBundleIdRouteChildren = {
  BundlesBundleIdDraftRoute: BundlesBundleIdDraftRoute,
  BundlesBundleIdManageRoute: BundlesBundleIdManageRoute,
  BundlesBundleIdIndexRoute: BundlesBundleIdIndexRoute,
}

const BundlesBundleIdRouteWithChildren = BundlesBundleIdRoute._addFileChildren(
  BundlesBundleIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  AboutRoute: AboutRoute,
  CollaborationsRoute: CollaborationsRoute,
  SettingsRoute: SettingsRoute,
  TosRoute: TosRoute,
  BundlesBundleIdRoute: BundlesBundleIdRouteWithChildren,
  BundlesUploadRoute: BundlesUploadRoute,
  UsersJointIdRoute: UsersJointIdRoute,
  BundlesIndexRoute: BundlesIndexRoute,
  UsersIndexRoute: UsersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
